[functions]
  directory = "functions"
  node_bundler = "esbuild"
[functions.command]
  command = "sendEmail.handler"

  [[headers]]
    for = '/*'
    [headers.values]
      Access-Control-Allow-Origin = '*'
      Access-Control-Allow-Methods = 'POST'
      Access-Control-Allow-Headers = 'Content-Type'
